#!/bin/bash

echo "=== Sistema de Filiais com Seed ==="
echo ""
echo "Uso: ./run_filial_N.sh [porta_seed]"
echo ""
echo "Exemplos:"
echo ""
echo "  # Primeira filial (sem seed - se torna líder):"
echo "  ./run_filial_1.sh"
echo ""
echo "  # Filiais seguintes (conectam ao seed na porta 9876):"
echo "  ./run_filial_2.sh 9876"
echo "  ./run_filial_3.sh 9876"
echo ""
